### ISSUE TITLE
mu (Palm OS) RetroArch - Installing Apps

### ISSUE THREAD

**Issue by Smoker1** [meepingsnesroms/Mu#44]
Was wondering if there was a way to Install Palm OS .prc Files?

**Comment by meepingsnesroms** [comment]
Not yet, in 2 releases when the SD card works I will add a way to install to the SD card.
The current way to install apps is by copying directly to RAM while the emu is running, this is not in the RetroArch build though because it can mess things up, its like unpluging your harddrive from your computer while its in sleep mode copying some files over and plugging it back in, but with RAM and while the CPU is still somewhat running.

You will be able to build your own RAM file and copy it over soon though.

**Comment by gingerbeardman** [comment]
Ah, I was wondering how to get my PRC files into the RetroArch build.

The way I would expect it working would be:
1. start core
2. look for palmos41-en-m515.rom in RetroArch system directory 
3. accept PRC file types, temporarily copy them into RAM and launch

It's odd, but given my experience with the PX68k core, RetroArch users do not seem to want persistent devices (even if that's how they are IRL) but rather a core as a device for running a game/app in demand.

**Comment by meepingsnesroms** [comment]
SD card support is working now.
